version: '3.9'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - app_net

  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - database
    networks:
      - app_net

  database:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net: